### ISSUE TITLE
the package json says node >= 8 supported, I believe currently FFI doesn't work on node >8

### ISSUE THREAD

**Issue by thedewpoint** [iotaeco/iota-pico-pow-nodejs#1]
I had this issue when using ffi and had to downgrade to node 8 in order to use it. Did you have this issue as well and if so how did you get around it?

Thank you!

**Comment by obany** [comment]
The node-ffi package that is currently on npm doesn't have all the latest pull requests in it, which fix some of the v9 problems.

I am running on windows for my development on node 9.5.0.

To get it working I did the following, because as you said it doesn't work out of the box on v9, but it should very soon.

git clone https://github.com/node-ffi/node-ffi.git
cd node-ffi
npm install
node-gyp rebuild
npm link

Then  using the symbolic link created by the "npm link" I connect it to my itoa-pico-pow-nodejs repo with
npm link ffi
and then all is well on v9 :)
